spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB 
  application:
    name: datamanager
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "[hibernate.jdbc.batch_size]": 50
        "[hibernate.order_inserts]": true
        "[hibernate.order_updates]": true
        "[hibernate.jdbc.batch_versioned_data]": true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000}
google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  maps:
    api-key: ${GOOGLE_MAPS_API_KEY}

app:
  superadmin:
    username: ${SUPERADMIN_USERNAME}
    password: ${SUPERADMIN_PASSWORD}
  frontend:
    url: http://localhost:3000

gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

 